// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;

public class TurboJpegDLL {

    TurboJpegDLL() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;
    private static final int TJFLAG_FASTDCT = (int)2048L;
    /**
     * {@snippet lang=c :
     * #define TJFLAG_FASTDCT 2048
     * }
     */
    public static int TJFLAG_FASTDCT() {
        return TJFLAG_FASTDCT;
    }
    private static final int TJSAMP_422 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum TJSAMP.TJSAMP_422 = 1
     * }
     */
    public static int TJSAMP_422() {
        return TJSAMP_422;
    }
    private static final int TJPF_RGB = (int)0L;
    /**
     * {@snippet lang=c :
     * enum TJPF.TJPF_RGB = 0
     * }
     */
    public static int TJPF_RGB() {
        return TJPF_RGB;
    }
    private static final int TJPF_BGR = (int)1L;
    /**
     * {@snippet lang=c :
     * enum TJPF.TJPF_BGR = 1
     * }
     */
    public static int TJPF_BGR() {
        return TJPF_BGR;
    }

    private static class tjDestroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_POINTER
        );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjDestroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int tjDestroy(tjhandle handle)
     * }
     */
    public static FunctionDescriptor tjDestroy$descriptor() {
        return tjDestroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int tjDestroy(tjhandle handle)
     * }
     */
    public static MethodHandle tjDestroy$handle() {
        return tjDestroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int tjDestroy(tjhandle handle)
     * }
     */
    public static MemorySegment tjDestroy$address() {
        return tjDestroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int tjDestroy(tjhandle handle)
     * }
     */
    public static int tjDestroy(MemorySegment handle) {
        var mh$ = tjDestroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjDestroy", handle);
            }
            return (int)mh$.invokeExact(handle);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjInitCompress {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_POINTER    );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjInitCompress");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tjhandle tjInitCompress()
     * }
     */
    public static FunctionDescriptor tjInitCompress$descriptor() {
        return tjInitCompress.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tjhandle tjInitCompress()
     * }
     */
    public static MethodHandle tjInitCompress$handle() {
        return tjInitCompress.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tjhandle tjInitCompress()
     * }
     */
    public static MemorySegment tjInitCompress$address() {
        return tjInitCompress.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tjhandle tjInitCompress()
     * }
     */
    public static MemorySegment tjInitCompress() {
        var mh$ = tjInitCompress.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjInitCompress");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjInitDecompress {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_POINTER    );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjInitDecompress");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * tjhandle tjInitDecompress()
     * }
     */
    public static FunctionDescriptor tjInitDecompress$descriptor() {
        return tjInitDecompress.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * tjhandle tjInitDecompress()
     * }
     */
    public static MethodHandle tjInitDecompress$handle() {
        return tjInitDecompress.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * tjhandle tjInitDecompress()
     * }
     */
    public static MemorySegment tjInitDecompress$address() {
        return tjInitDecompress.ADDR;
    }

    /**
     * {@snippet lang=c :
     * tjhandle tjInitDecompress()
     * }
     */
    public static MemorySegment tjInitDecompress() {
        var mh$ = tjInitDecompress.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjInitDecompress");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjDecompressHeader2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_LONG,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER
        );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjDecompressHeader2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int tjDecompressHeader2(tjhandle handle, unsigned char *jpegBuf, unsigned long jpegSize, int *width, int *height, int *jpegSubsamp)
     * }
     */
    public static FunctionDescriptor tjDecompressHeader2$descriptor() {
        return tjDecompressHeader2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int tjDecompressHeader2(tjhandle handle, unsigned char *jpegBuf, unsigned long jpegSize, int *width, int *height, int *jpegSubsamp)
     * }
     */
    public static MethodHandle tjDecompressHeader2$handle() {
        return tjDecompressHeader2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int tjDecompressHeader2(tjhandle handle, unsigned char *jpegBuf, unsigned long jpegSize, int *width, int *height, int *jpegSubsamp)
     * }
     */
    public static MemorySegment tjDecompressHeader2$address() {
        return tjDecompressHeader2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int tjDecompressHeader2(tjhandle handle, unsigned char *jpegBuf, unsigned long jpegSize, int *width, int *height, int *jpegSubsamp)
     * }
     */
    public static int tjDecompressHeader2(MemorySegment handle, MemorySegment jpegBuf, int jpegSize, MemorySegment width, MemorySegment height, MemorySegment jpegSubsamp) {
        var mh$ = tjDecompressHeader2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjDecompressHeader2", handle, jpegBuf, jpegSize, width, height, jpegSubsamp);
            }
            return (int)mh$.invokeExact(handle, jpegBuf, jpegSize, width, height, jpegSubsamp);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjCompress2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT
        );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjCompress2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int tjCompress2(tjhandle handle, const unsigned char *srcBuf, int width, int pitch, int height, int pixelFormat, unsigned char **jpegBuf, unsigned long *jpegSize, int jpegSubsamp, int jpegQual, int flags)
     * }
     */
    public static FunctionDescriptor tjCompress2$descriptor() {
        return tjCompress2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int tjCompress2(tjhandle handle, const unsigned char *srcBuf, int width, int pitch, int height, int pixelFormat, unsigned char **jpegBuf, unsigned long *jpegSize, int jpegSubsamp, int jpegQual, int flags)
     * }
     */
    public static MethodHandle tjCompress2$handle() {
        return tjCompress2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int tjCompress2(tjhandle handle, const unsigned char *srcBuf, int width, int pitch, int height, int pixelFormat, unsigned char **jpegBuf, unsigned long *jpegSize, int jpegSubsamp, int jpegQual, int flags)
     * }
     */
    public static MemorySegment tjCompress2$address() {
        return tjCompress2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int tjCompress2(tjhandle handle, const unsigned char *srcBuf, int width, int pitch, int height, int pixelFormat, unsigned char **jpegBuf, unsigned long *jpegSize, int jpegSubsamp, int jpegQual, int flags)
     * }
     */
    public static int tjCompress2(MemorySegment handle, MemorySegment srcBuf, int width, int pitch, int height, int pixelFormat, MemorySegment jpegBuf, MemorySegment jpegSize, int jpegSubsamp, int jpegQual, int flags) {
        var mh$ = tjCompress2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjCompress2", handle, srcBuf, width, pitch, height, pixelFormat, jpegBuf, jpegSize, jpegSubsamp, jpegQual, flags);
            }
            return (int)mh$.invokeExact(handle, srcBuf, width, pitch, height, pixelFormat, jpegBuf, jpegSize, jpegSubsamp, jpegQual, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjDecompress2 {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_LONG,
            TurboJpegDLL.C_POINTER,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT,
            TurboJpegDLL.C_INT
        );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjDecompress2");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int tjDecompress2(tjhandle handle, const unsigned char *jpegBuf, unsigned long jpegSize, unsigned char *dstBuf, int width, int pitch, int height, int pixelFormat, int flags)
     * }
     */
    public static FunctionDescriptor tjDecompress2$descriptor() {
        return tjDecompress2.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int tjDecompress2(tjhandle handle, const unsigned char *jpegBuf, unsigned long jpegSize, unsigned char *dstBuf, int width, int pitch, int height, int pixelFormat, int flags)
     * }
     */
    public static MethodHandle tjDecompress2$handle() {
        return tjDecompress2.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int tjDecompress2(tjhandle handle, const unsigned char *jpegBuf, unsigned long jpegSize, unsigned char *dstBuf, int width, int pitch, int height, int pixelFormat, int flags)
     * }
     */
    public static MemorySegment tjDecompress2$address() {
        return tjDecompress2.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int tjDecompress2(tjhandle handle, const unsigned char *jpegBuf, unsigned long jpegSize, unsigned char *dstBuf, int width, int pitch, int height, int pixelFormat, int flags)
     * }
     */
    public static int tjDecompress2(MemorySegment handle, MemorySegment jpegBuf, int jpegSize, MemorySegment dstBuf, int width, int pitch, int height, int pixelFormat, int flags) {
        var mh$ = tjDecompress2.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjDecompress2", handle, jpegBuf, jpegSize, dstBuf, width, pitch, height, pixelFormat, flags);
            }
            return (int)mh$.invokeExact(handle, jpegBuf, jpegSize, dstBuf, width, pitch, height, pixelFormat, flags);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class tjFree {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            TurboJpegDLL.C_POINTER
        );

        public static final MemorySegment ADDR = TurboJpegDLL.findOrThrow("tjFree");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void tjFree(unsigned char *buffer)
     * }
     */
    public static FunctionDescriptor tjFree$descriptor() {
        return tjFree.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void tjFree(unsigned char *buffer)
     * }
     */
    public static MethodHandle tjFree$handle() {
        return tjFree.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void tjFree(unsigned char *buffer)
     * }
     */
    public static MemorySegment tjFree$address() {
        return tjFree.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void tjFree(unsigned char *buffer)
     * }
     */
    public static void tjFree(MemorySegment buffer) {
        var mh$ = tjFree.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("tjFree", buffer);
            }
            mh$.invokeExact(buffer);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

