// Generated by jextract

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class WebcamDLL extends WebcamDLL$shared {

    WebcamDLL() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class getCameras {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_INT,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_INT,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("getCameras");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t getCameras(Camera cameras[], uint32_t maxCameraCount, wchar_t *log, int64_t logByteCount)
     * }
     */
    public static FunctionDescriptor getCameras$descriptor() {
        return getCameras.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t getCameras(Camera cameras[], uint32_t maxCameraCount, wchar_t *log, int64_t logByteCount)
     * }
     */
    public static MethodHandle getCameras$handle() {
        return getCameras.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t getCameras(Camera cameras[], uint32_t maxCameraCount, wchar_t *log, int64_t logByteCount)
     * }
     */
    public static MemorySegment getCameras$address() {
        return getCameras.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t getCameras(Camera cameras[], uint32_t maxCameraCount, wchar_t *log, int64_t logByteCount)
     * }
     */
    public static int getCameras(MemorySegment cameras, int maxCameraCount, MemorySegment log, long logByteCount) {
        var mh$ = getCameras.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("getCameras", cameras, maxCameraCount, log, logByteCount);
            }
            return (int)mh$.invokeExact(cameras, maxCameraCount, log, logByteCount);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class connectCamera {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_BOOL,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_INT,
            WebcamDLL.C_INT,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("connectCamera");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool connectCamera(const wchar_t *devicePath, int32_t width, int32_t height, void (*handler)(uint8_t *, int32_t, int32_t, int32_t), wchar_t *log, int64_t logByteCount)
     * }
     */
    public static FunctionDescriptor connectCamera$descriptor() {
        return connectCamera.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool connectCamera(const wchar_t *devicePath, int32_t width, int32_t height, void (*handler)(uint8_t *, int32_t, int32_t, int32_t), wchar_t *log, int64_t logByteCount)
     * }
     */
    public static MethodHandle connectCamera$handle() {
        return connectCamera.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool connectCamera(const wchar_t *devicePath, int32_t width, int32_t height, void (*handler)(uint8_t *, int32_t, int32_t, int32_t), wchar_t *log, int64_t logByteCount)
     * }
     */
    public static MemorySegment connectCamera$address() {
        return connectCamera.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool connectCamera(const wchar_t *devicePath, int32_t width, int32_t height, void (*handler)(uint8_t *, int32_t, int32_t, int32_t), wchar_t *log, int64_t logByteCount)
     * }
     */
    public static boolean connectCamera(MemorySegment devicePath, int width, int height, MemorySegment handler, MemorySegment log, long logByteCount) {
        var mh$ = connectCamera.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("connectCamera", devicePath, width, height, handler, log, logByteCount);
            }
            return (boolean)mh$.invokeExact(devicePath, width, height, handler, log, logByteCount);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class disconnectCamera {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_BOOL,
            WebcamDLL.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("disconnectCamera");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool disconnectCamera(const wchar_t *devicePath)
     * }
     */
    public static FunctionDescriptor disconnectCamera$descriptor() {
        return disconnectCamera.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool disconnectCamera(const wchar_t *devicePath)
     * }
     */
    public static MethodHandle disconnectCamera$handle() {
        return disconnectCamera.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool disconnectCamera(const wchar_t *devicePath)
     * }
     */
    public static MemorySegment disconnectCamera$address() {
        return disconnectCamera.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool disconnectCamera(const wchar_t *devicePath)
     * }
     */
    public static boolean disconnectCamera(MemorySegment devicePath) {
        var mh$ = disconnectCamera.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("disconnectCamera", devicePath);
            }
            return (boolean)mh$.invokeExact(devicePath);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class checkForCameraEvent {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_INT,
            WebcamDLL.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("checkForCameraEvent");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t checkForCameraEvent(const wchar_t *devicePath)
     * }
     */
    public static FunctionDescriptor checkForCameraEvent$descriptor() {
        return checkForCameraEvent.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t checkForCameraEvent(const wchar_t *devicePath)
     * }
     */
    public static MethodHandle checkForCameraEvent$handle() {
        return checkForCameraEvent.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t checkForCameraEvent(const wchar_t *devicePath)
     * }
     */
    public static MemorySegment checkForCameraEvent$address() {
        return checkForCameraEvent.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t checkForCameraEvent(const wchar_t *devicePath)
     * }
     */
    public static int checkForCameraEvent(MemorySegment devicePath) {
        var mh$ = checkForCameraEvent.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("checkForCameraEvent", devicePath);
            }
            return (int)mh$.invokeExact(devicePath);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class setCameraSetting {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_BOOL,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_INT,
            WebcamDLL.C_INT,
            WebcamDLL.C_BOOL,
            WebcamDLL.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("setCameraSetting");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * _Bool setCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum, _Bool isManual, int32_t manualValue)
     * }
     */
    public static FunctionDescriptor setCameraSetting$descriptor() {
        return setCameraSetting.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * _Bool setCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum, _Bool isManual, int32_t manualValue)
     * }
     */
    public static MethodHandle setCameraSetting$handle() {
        return setCameraSetting.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * _Bool setCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum, _Bool isManual, int32_t manualValue)
     * }
     */
    public static MemorySegment setCameraSetting$address() {
        return setCameraSetting.ADDR;
    }

    /**
     * {@snippet lang=c :
     * _Bool setCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum, _Bool isManual, int32_t manualValue)
     * }
     */
    public static boolean setCameraSetting(MemorySegment devicePath, int interfaceEnum, int settingEnum, boolean isManual, int manualValue) {
        var mh$ = setCameraSetting.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("setCameraSetting", devicePath, interfaceEnum, settingEnum, isManual, manualValue);
            }
            return (boolean)mh$.invokeExact(devicePath, interfaceEnum, settingEnum, isManual, manualValue);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class getCameraSetting {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            WebcamDLL.C_LONG_LONG,
            WebcamDLL.C_POINTER,
            WebcamDLL.C_INT,
            WebcamDLL.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("getCameraSetting");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int64_t getCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum)
     * }
     */
    public static FunctionDescriptor getCameraSetting$descriptor() {
        return getCameraSetting.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int64_t getCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum)
     * }
     */
    public static MethodHandle getCameraSetting$handle() {
        return getCameraSetting.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int64_t getCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum)
     * }
     */
    public static MemorySegment getCameraSetting$address() {
        return getCameraSetting.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int64_t getCameraSetting(const wchar_t *devicePath, int32_t interfaceEnum, int32_t settingEnum)
     * }
     */
    public static long getCameraSetting(MemorySegment devicePath, int interfaceEnum, int settingEnum) {
        var mh$ = getCameraSetting.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("getCameraSetting", devicePath, interfaceEnum, settingEnum);
            }
            return (long)mh$.invokeExact(devicePath, interfaceEnum, settingEnum);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

